name: leyana
description: "A new Flutter project."

publish_to: "none"

version: 1.2.0+5

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  faker: ^2.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  dio: ^5.5.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  share_plus: ^9.0.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.1+1
  timezone: ^0.9.4
  flutter_timezone: ^2.0.1
  logger: ^2.3.0
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  flutter_exit_app: ^1.1.4
  go_router: ^14.2.7
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "icon.png"
  min_sdk_android: 21

flutter_native_splash:
  image: icon.png
  color: "#ffffff"
  color_dark: "#1D140C"
